# Numpy Commands

In [2]:
import numpy as np

In [3]:
# Creating a NumPy array from a list
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
# Creating a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Generating a range of numbers
range_arr = np.arange(0, 10, 2)
print(range_arr)


[0 2 4 6 8]


In [6]:
# Creating array object
arr = np.array( [[ 1, 2, 3],[ 4, 5, 6]] )

In [7]:
# Printing type of arr object
print("Array is of type: ", type(arr))

Array is of type:  <class 'numpy.ndarray'>


In [8]:
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

No. of dimensions:  2


In [9]:
# Printing shape of array
print("Shape of array: ", arr.shape)

Shape of array:  (2, 3)


In [10]:
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

Size of array:  6


In [11]:
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array stores elements of type:  int32


In [12]:
# Creating a 2X3 array with all zeros
zeros_arr = np.zeros((2, 3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# Create an array with random values
e = np.random.random((3, 3))
print ("A random array:\n", e)
print(np.random.randint(1, 10, (2, 3))) # 2x3 array of random integers from 1 to 10

A random array:
 [[0.03593743 0.90427346 0.43620575]
 [0.6492901  0.08996471 0.68654954]
 [0.04548113 0.55802698 0.86017667]]
[[2 2 5]
 [6 8 8]]


In [ ]:
# Create a constant value array of float type
con_v = np.full((3, 3), 6,dtype='float')
print(con_v)